font_family      CaskaydiaCove Nerd Font Mono
font_size        10.0
bold_font        auto
italic_font      auto
bold_italic_font auto

enable_audio_bell no

window_padding_width 10
placement_strategy center
cursor_trail 3
dynamic_background_opacity yes
background_opacity 0.80

dynamic_background_opacity on

#hide_window_decorations yes

allow_remote_control yes

confirm_os_window_close 0

# initially empty, to be configured by user and remains static
include userprefs.conf

# Note: as userprefs.conf is included at the end, settings configured in this file will override the defaults


include ~/.config/kitty/colors.conf
