### --- Настройки вывода (Исправляют задержку на внешнем монике) ---
vo=gpu                       # Современный вывод, лучше работает в Wayland
gpu-context=wayland          # Принудительно используем Wayland контекст
hwdec=vaapi                  # Аппаратное ускорение через Intel QuickSync
# hwdec=no                   # Если всё равно гаснет, закомментируй строку выше и раскомментируй эту
