# █ █▄ █ █▀▀ █   █ █ █▀▄ █▀▀ 
# █ █ ▀█ █▄▄ █▄▄ █▄█ █▄▀ ██▄
#
# just a little decentralization, you know?

source = ~/.config/hypr/config/animations.conf																			#include animations config
source = ~/.config/hypr/config/autostart.conf																			#include autostart config
source = ~/.config/hypr/config/common.conf																				#include common config
source = ~/.config/hypr/config/env.conf																					#include environment config
source = ~/.config/hypr/config/input.conf																				#include input config
source = ~/.config/hypr/config/keybinds.conf																			#include keybinds config
source = ~/.config/hypr/config/layouts.conf																				#include layouts config
source = ~/.config/hypr/config/misc.conf																				#include misc config
source = ~/.config/hypr/config/monitors.conf																			#include monitors config
source = ~/.config/hypr/config/style.conf																				#include style config
source = ~/.config/hypr/config/variables.conf																			#include variables config
source = ~/.config/hypr/config/windowrules.conf																			#include window rules config
