[mgr]
sort_by	= "alphabetical"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
sort_translit = false
linemode = "size"
show_hidden = true
show_symlink = true
scrolloff = 5
mouse_events = [ "click", "scroll" ]
title_format = "Yazi: {cwd}"

[opener]
read = [
    { run = 'bat "$@"', block = true, desc = "Read with Bat" }
]
edit = [
    { run = 'nvim "$@"', block = true, desc = "NeoVim" }
]
view = [
    { run = 'imv "$@"', detach = true, desc = "View Image" }
]
play = [
    { run = 'mpv "$@"', detach = true, desc = "Play Video" }
]

[open]
rules = [
    { url = "*.conf",	use = ["edit", "read"] },
    { url = "*.json",	use = ["edit", "read"] },
    { url = "*.lua",	use = ["edit", "read"] },
    { url = "*.txt",	use = ["edit", "read"] },

    { mime = "text/*",  use = ["edit", "read"] },

    { url = "*.pdf",   use = "view" }, 
    { mime = "image/*", use = "view" },

    { mime = "video/*", use = "play" },

	{ url = "*",       use = "edit" }
]

[preview]
graphics_protocol = "kitty"
