# Hand-writed by flassuu
# btop theme template

# Main background; leave empty only if you need terminal transparency
theme[main_bg]="#111314"

# Main text / titles
theme[main_fg]="#b3b8c3"
theme[title]="#b3b8c3"

# Highlight / shortcut color
theme[hi_fg]="#85a7a5"

# Selected item in process list
theme[selected_bg]="#303537"
theme[selected_fg]="#85a7a5"

# Inactive / disabled text
theme[inactive_fg]="#111314"

# Text on top of graphs
theme[graph_text]="#ffffff"

# Meter background
theme[meter_bg]="#303537"

# Misc text in processes box
theme[proc_misc]="#ffffff"

# Box outline colors
theme[cpu_box]="#7d8fa4"
theme[mem_box]="#87b379"
theme[net_box]="#b04b57"
theme[proc_box]="#85a7a5"

# Divider line / small box lines
theme[div_line]="#7d8fa4"

# Temperature graph gradient
theme[temp_start]="#87b379"
theme[temp_mid]="#e5c179"
theme[temp_end]="#b04b57"

# CPU graph gradient
theme[cpu_start]="#85a7a5"
theme[cpu_mid]="#85a7a5"
theme[cpu_end]="#7d8fa4"

# Free memory/disk meter gradient
theme[free_start]="#7d8fa4"
theme[free_mid]="#85a7a5"
theme[free_end]="#7d8fa4"

# Cached memory/disk meter gradient
theme[cached_start]="#85a7a5"
theme[cached_mid]="#7d8fa4"
theme[cached_end]="#85a7a5"

# Available memory/disk meter gradient
theme[available_start]="#e5c179"
theme[available_mid]="#b04b57"
theme[available_end]="#b04b57"

# Used memory/disk meter gradient
theme[used_start]="#87b379"
theme[used_mid]="#85a7a5"
theme[used_end]="#85a7a5"

# Download graph gradient
theme[download_start]="#e5c179"
theme[download_mid]="#b04b57"
theme[download_end]="#b04b57"

# Upload graph gradient
theme[upload_start]="#87b379"
theme[upload_mid]="#85a7a5"
theme[upload_end]="#85a7a5"

# Process box gradient
theme[process_start]="#85a7a5"
theme[process_mid]="#85a7a5"
theme[process_end]="#7d8fa4"
