# Hand-writed by flassuu
# btop theme template

# Main background; leave empty only if you need terminal transparency
theme[main_bg]="{{ base.background.hex }}"

# Main text / titles
theme[main_fg]="{{ base.foreground.hex }}"
theme[title]="{{ base.foreground.hex }}"

# Highlight / shortcut color
theme[hi_fg]="{{ accent.secondary.hex }}"

# Selected item in process list
theme[selected_bg]="{{ ui.surface2.hex }}"
theme[selected_fg]="{{ accent.secondary.hex }}"

# Inactive / disabled text
theme[inactive_fg]="{{ ui.inactive.hex }}"

# Text on top of graphs
theme[graph_text]="{{ base.cursor.hex }}"

# Meter background
theme[meter_bg]="{{ ui.surface2.hex }}"

# Misc text in processes box
theme[proc_misc]="{{ base.cursor.hex }}"

# Box outline colors
theme[cpu_box]="{{ accent.primary.hex }}"
theme[mem_box]="{{ state.success.hex }}"
theme[net_box]="{{ state.error.hex }}"
theme[proc_box]="{{ accent.secondary.hex }}"

# Divider line / small box lines
theme[div_line]="{{ ui.border.hex }}"

# Temperature graph gradient
theme[temp_start]="{{ state.success.hex }}"
theme[temp_mid]="{{ state.warning.hex }}"
theme[temp_end]="{{ state.error.hex }}"

# CPU graph gradient
theme[cpu_start]="{{ normal.cyan.hex }}"
theme[cpu_mid]="{{ accent.secondary.hex }}"
theme[cpu_end]="{{ accent.primary.hex }}"

# Free memory/disk meter gradient
theme[free_start]="{{ accent.primary.hex }}"
theme[free_mid]="{{ accent.secondary.hex }}"
theme[free_end]="{{ normal.blue.hex }}"

# Cached memory/disk meter gradient
theme[cached_start]="{{ normal.cyan.hex }}"
theme[cached_mid]="{{ normal.blue.hex }}"
theme[cached_end]="{{ accent.secondary.hex }}"

# Available memory/disk meter gradient
theme[available_start]="{{ state.warning.hex }}"
theme[available_mid]="{{ normal.red.hex }}"
theme[available_end]="{{ state.error.hex }}"

# Used memory/disk meter gradient
theme[used_start]="{{ state.success.hex }}"
theme[used_mid]="{{ normal.cyan.hex }}"
theme[used_end]="{{ accent.secondary.hex }}"

# Download graph gradient
theme[download_start]="{{ state.warning.hex }}"
theme[download_mid]="{{ normal.red.hex }}"
theme[download_end]="{{ state.error.hex }}"

# Upload graph gradient
theme[upload_start]="{{ state.success.hex }}"
theme[upload_mid]="{{ normal.cyan.hex }}"
theme[upload_end]="{{ accent.secondary.hex }}"

# Process box gradient
theme[process_start]="{{ normal.cyan.hex }}"
theme[process_mid]="{{ accent.secondary.hex }}"
theme[process_end]="{{ accent.primary.hex }}"
