-- Generated by matugen for Hyprland (Lua config) — flassuu
return {
    background = "rgba({{ base.background.hex_stripped }}ff)",
    foreground = "rgba({{ base.foreground.hex_stripped }}ff)",
    cursor     = "rgba({{ base.cursor.hex_stripped }}ff)",

    surface  = "rgba({{ ui.surface.hex_stripped }}ff)",
    surface2 = "rgba({{ ui.surface2.hex_stripped }}ff)",
    surface3 = "rgba({{ ui.surface3.hex_stripped }}ff)",
    border   = "rgba({{ ui.border.hex_stripped }}ff)",
    inactive = "rgba({{ ui.inactive.hex_stripped }}ff)",

    primary   = "rgba({{ accent.primary.hex_stripped }}ff)",
    secondary = "rgba({{ accent.secondary.hex_stripped }}ff)",
    tertiary  = "rgba({{ accent.tertiary.hex_stripped }}ff)",

    error   = "rgba({{ state.error.hex_stripped }}ff)",
    warning = "rgba({{ state.warning.hex_stripped }}ff)",
    success = "rgba({{ state.success.hex_stripped }}ff)",
}