# Hand-writed by flassuu
background {{ base.background.hex }}
foreground {{ base.foreground.hex }}
selection_background {{ base.foreground.hex }}
selection_foreground {{ base.background.hex }}
cursor {{ base.cursor.hex }}
cursor_text_color {{ ui.border.hex }}

color0 {{ normal.black.hex }}
color1 {{ normal.red.hex }}
color2 {{ normal.green.hex }}
color3 {{ normal.yellow.hex }}
color4 {{ normal.blue.hex }}
color5 {{ normal.magenta.hex }}
color6 {{ normal.cyan.hex }}
color7 {{ normal.white.hex }}
color8 {{ bright.black.hex }}
color9 {{ bright.red.hex }}
color10 {{ bright.green.hex }}
color11 {{ bright.yellow.hex }}
color12 {{ bright.blue.hex }}
color13 {{ bright.magenta.hex }}
color14 {{ bright.cyan.hex }}
color15 {{ bright.white.hex }}
