# ▄▀█ █ █ ▀█▀ █▀█ █▀ ▀█▀ ▄▀█ █▀█ ▀█▀
# █▀█ █▄█  █  █▄█ ▄█  █  █▀█ █▀▄  █ 
#
# processes that will start with your system

source = ~/.config/hypr/config/variables.conf																			# include variables config

# scripts
#

exec-once = $scrPath/awww-watcher																			# save curent wallpaper as file to cache

# apps
#

exec-once = waybar																							    # launch system bar
exec-once = awww-daemon																							# launch wallpaper daemon
exec-once = hypridle																							# launch hypridle
exec-once = easyeffects																							# launch sound control

exec-once = wl-paste -t text --watch clipman store																# launch clipman
