-- █▀▀ █▀█ █  █▀█ █▀█ █▀
-- █▄▄ █▄█ █▄ █▄█ █▀▄ ▄█
--
-- Colors: Material You palette generated by matugen, drives borders and decoration.
-- Docs: https://wiki.hypr.land/configuring/core/variables/
-- matugen: https://github.com/InioX/matugen
return {
	background = "rgba(111314ff)",
	foreground = "rgba(b3b8c3ff)",
	cursor = "rgba(ffffffff)",

	surface = "rgba(202425ff)",
	surface2 = "rgba(303537ff)",
	surface3 = "rgba(343d46ff)",
	border = "rgba(7d8fa4ff)",
	inactive = "rgba(111314ff)",

	primary = "rgba(7d8fa4ff)",
	secondary = "rgba(85a7a5ff)",
	tertiary = "rgba(a47996ff)",

	error = "rgba(b04b57ff)",
	warning = "rgba(e5c179ff)",
	success = "rgba(87b379ff)",
}
