-- Generated by matugen (template: hyprland.lua) — не редактировать вручную
return {
    background = "rgba(1e1e2eff)",
    foreground = "rgba(cdd6f4ff)",
    cursor     = "rgba(f5e0dcff)",

    surface  = "rgba(313244ff)",
    surface2 = "rgba(45475aff)",
    surface3 = "rgba(585b70ff)",
    border   = "rgba(6c7086ff)",
    inactive = "rgba(7f849cff)",

    primary   = "rgba(cba6f7ff)",
    secondary = "rgba(89b4faff)",
    tertiary  = "rgba(f5c2e7ff)",

    error   = "rgba(f38ba8ff)",
    warning = "rgba(fab387ff)",
    success = "rgba(a6e3a1ff)",
}