# █   ▄▀█ █▄█ █▀█ █ █ ▀█▀ █▀
# █▄▄ █▀█  █  █▄█ █▄█  █  ▄█
#
# idk
#
# see https://wiki.hyprland.org/Configuring/Dwindle-Layout/
# see https://wiki.hyprland.org/Configuring/Master-Layout/

dwindle {
    preserve_split = yes
}


#master {
#    new_status = master
#}
