# █ █ ▄▀█ █▀█ █ ▄▀█ █▄▄ █   █▀▀ █▀
# ▀▄▀ █▀█ █▀▄ █ █▀█ █▄█ █▄▄ ██▄ ▄█


# Path
$scrPath = ~/.local/bin	 																							# default scripts path
																							
# Assign apps
$term = kitty
$menu = rofi -show drun -show-icons
$file = $term -e yazi
$browser = firefox
$office = libreoffice
$lockscreen = hyprlock
$code = $term -e nvim
$clipboard = clipman pick -t rofi

